@startuml
actor Passenger
actor Airline
boundary DApp
control FlightSuretyApp
control FlightSuretyData
control Oracle
database FlightSuretyDB

autonumber "<b>[000]"
Passenger -> DApp : request buy a flight insurance
DApp -> FlightSuretyApp : buy(string calldata airlineName,string calldata flightName,uint256 timestamp,string calldata passengerName)
FlightSuretyApp -> FlightSuretyData: insurance
FlightSuretyData -> FlightSuretyData : update insurace list (by passenger, by flight)
@enduml